"""
generate_data.py
----------------
Run this script ONCE to produce data.js which the UI reads.
Must be run from the UI/ folder, or adjust the paths below.

Usage:
    cd UI
    python generate_data.py
"""

import sys
import json
import numpy as np
import pandas as pd
from xgboost import XGBRegressor
from pathlib import Path

# ── Paths (adjust if running from a different directory) ──────────────────────

MODEL_PATH = "../xgb_v4_OTA2201_20260602_1457.ubj"
DATA_PATH  = "../../../Data_Processing/preprocessed_data.csv"
OUT_PATH   = "data.js"

# ── Load model ────────────────────────────────────────────────────────────────

print("Loading model...")
model = XGBRegressor()
model.load_model(MODEL_PATH)

# ── Load + preprocess data (identical to v4_search) ──────────────────────────

print("Loading and preprocessing data...")
df = pd.read_csv(DATA_PATH)
df["datetime_utc12"] = pd.to_datetime(df["datetime_utc12"])
df = df.sort_values("datetime_utc12").reset_index(drop=True)
df = df.ffill()

target_col = "el_price_dol_MWh_OTA2201"

cols_to_shift_24h = [
    c for c in df.columns if "el_price" in c and c != target_col
] + [
    "Coal","Diesel","Ele","Gas","Geo","Hydro","Solar","Wind","Wood",
    "demand_GWh_CNI","demand_GWh_LNI","demand_GWh_LSI","demand_GWh_UNI","demand_GWh_USI",
    "avg_flow_MW","peak_flow_MW","Direction"
]
for col in cols_to_shift_24h:
    df[f"{col}_lag24"] = df[col].shift(24)
    df = df.drop(columns=[col])

df["hour"]       = df["datetime_utc12"].dt.hour
df["dayofweek"]  = df["datetime_utc12"].dt.dayofweek
df["month"]      = df["datetime_utc12"].dt.month
df["dayofyear"]  = df["datetime_utc12"].dt.dayofyear
df["is_weekend"] = df["dayofweek"].isin([5,6]).astype(int)
df["hour_sin"]   = np.sin(2*np.pi*df["hour"]/24)
df["hour_cos"]   = np.cos(2*np.pi*df["hour"]/24)
df["dow_sin"]    = np.sin(2*np.pi*df["dayofweek"]/7)
df["dow_cos"]    = np.cos(2*np.pi*df["dayofweek"]/7)
df["month_sin"]  = np.sin(2*np.pi*df["month"]/12)
df["month_cos"]  = np.cos(2*np.pi*df["month"]/12)

df["target_lag_24h"]   = df[target_col].shift(24)
df["target_lag_168h"]  = df[target_col].shift(168)
df["target_lag_8760h"] = df[target_col].shift(8760)

for window in [24, 168, 8760]:
    shifted = df[target_col].shift(1)
    df[f"rolling_mean_{window}h"] = shifted.rolling(window).mean()
    df[f"rolling_std_{window}h"]  = shifted.rolling(window).std()

df = df.dropna().reset_index(drop=True)

exclude_cols = ["datetime_utc12", target_col]
feature_cols = [c for c in df.columns if c not in exclude_cols]

# ── Predict all of 2024 ───────────────────────────────────────────────────────

print("Predicting all 2024 days...")
days_data = []

for date in pd.date_range("2024-01-01", "2024-12-31", freq="D"):
    mask = (
        (df["datetime_utc12"] >= date) &
        (df["datetime_utc12"] <  date + pd.Timedelta(hours=24))
    )
    day_df = df[mask]
    if len(day_df) < 24:
        continue

    pred   = model.predict(day_df[feature_cols].values).tolist()
    actual = day_df[target_col].values.tolist()
    naive  = day_df["target_lag_24h"].values.tolist()

    days_data.append({
        "date":      str(date.date()),
        "predicted": [round(v, 2) for v in pred],
        "actual":    [round(v, 2) for v in actual],
        "naive":     [round(v, 2) for v in naive],
    })

print(f"  {len(days_data)} days computed.")

# ── Find demo day (2024-07-05) ────────────────────────────────────────────────

demo = next((d for d in days_data if d["date"] == "2024-07-05"), days_data[185])
print(f"Demo day: {demo['date']}")

# ── Write data.js ─────────────────────────────────────────────────────────────

js = f"""// Auto-generated by generate_data.py — do not edit manually.
// Contains hourly predicted / actual / naive prices for all of 2024.

const DEMO_DAY = {json.dumps(demo, indent=2)};

const DAYS_2024 = {json.dumps(days_data, indent=2)};
"""

Path(OUT_PATH).write_text(js)
print(f"\ndata.js written ({Path(OUT_PATH).stat().st_size // 1024} KB)")

# ── Also write data.json for the Streamlit app ───────────────────────────────

json_out = {"demo_day": demo, "days_2024": days_data}
Path("data.json").write_text(json.dumps(json_out))
print(f"data.json written ({Path('data.json').stat().st_size // 1024} KB)")

print("\nHTML UI : open UI/index.html in your browser.")
print("Streamlit: run  streamlit run app.py")
